import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <style jsx> 
        {`
        
        `}
      </style>
     
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
        
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='span'>Hunting Coder</span>
        </h1>
        <div className={styles.imagewrap}>
                  <img className={styles.myimg} src="/homeimg.jpg" width={200} height={200} alt='huntingcoder' />

        </div>


        <p className={styles.description}>
        A blog for Nextjs beginners          
        </p>
              
      </main>
    </div>
  )
}
